[package]
name = "pong"
version = "0.1.0"
authors = ["Fabio Elizandro <fabio@elizandro.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.amethyst]
version = "0.15"
features = ["metal"]